apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - name: simple-http
    image: python:2.7
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; sleep 8; python -m SimpleHTTPServer 8080"]
    ports:
    - name: http
      containerPort: 8080
    # readinessProbe:
    #   tcpSocket:
    #     port: 8080
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    # livenessProbe:
    #   tcpSocket:
    #     port: 8080
    #   initialDelaySeconds: 15
    #   periodSeconds: 20