apiVersion: v1
kind: Pod
metadata:
  name: secret_busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
      - name: secret_key
        mountPath: "/tmp/apikey"
        readOnly: true
  volumes:
  - name: secret_key
    secret:
      secretName: my-secret